name: push-release
on:
  push:
    tags-ignore:
      - rc-[0-9]+.[0-9]+.[0-9]+
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: lint
        run: |
          npm run lint
      - name: test
        run: |
          npm run test
