name: push-build-release
on:
  push:
    branch:
      - master
    tags:
      - rc-[0-9]+.[0-9]+.[0-9]+
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
      X_ORG_ID: ${{ secrets.X_ORG_ID }}
      TICKET_ID: ${{ secrets.TICKET_ID }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: build-app
        run: |
          npm ci
      - name: tsc
        run: npm run ts
      - name: test
        run: npm run test
      - name: lint
        run: npm run lint
      - name: set ticket
        run: |
          node ./scenarios/createRelease.js

  docker:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: build-app
        run: |
          npm ci
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: pavelgq/app:latest
          mytag: ${{ github.repository }}:${{ github.ref_name }}
      - name: add comment
        run: |
          node ./scenarios/buildDocker.js
