name: push-check-code
on:
  push:
    branches:
      - "*"
    tags-ignore:
      - rc-[0-9]+.[0-9]+.[0-9]+
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install
        run: |
          npm ci
      - name: Lint
        run: |
          npm run lint
      - name: Test
        run: |
          npm run test
