name: push-build-release
on:
  push:
    branch:
      - master
    tags:
      - rc-[0-9]+.[0-9]+.[0-9]+
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
  install:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: build-app
        run: |
          npm install
  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - run: npm run test
  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint
  release:
    needs: test
    runs-on: ubuntu-latest
    env:
      OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
      X_ORG_ID: ${{ secrets.X_ORG_ID }}
      TICKET_ID: ${{ secrets.TICKET_ID }}
    steps:
      - name: set ticket
        run: |
          node ./scenarios/Release.js
  docker:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ github.repository }}:${{ github.ref_name }}
      - name: add comment
        run: |
          node ./scenarios/Docker.js
